/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monstock;

import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YASSOU
 */
public class gestionstock extends javax.swing.JFrame {
    Statement stm,stm1;
    connexion maconx =new connexion();
    DefaultTableModel model;
    int selectedrow;
   
    /**
     * Creates new form gestionstock
     */
    public gestionstock() {
    
         initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        icon();
        model=(DefaultTableModel) tab_stock.getModel();
         affiche_stock();
    }

        void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo1.jpg")));
    }
        
    public void affiche_stock(){
   
       String requete_stock="SELECT * FROM stock";
        try{
            stm=maconx.obtenircnx().createStatement();
            ResultSet res=stm.executeQuery(requete_stock);
            
            
            while(res.next()){
                Vector v=new Vector();
                
                for(int i=0;i<model.getColumnCount();i++){
                    v.add(res.getInt("id_stock"));
                    v.add(res.getString("code_art"));
                     v.add(res.getString("desg_art"));
                      v.add(res.getInt("qte"));
                       v.add(res.getString("prix_vente"));
                       v.add(res.getInt("qte")*res.getInt("prix_vente"));
                       
                }
                
                model.addRow(v);
            }
        }catch(SQLException ex){
           JOptionPane.showMessageDialog(this,ex.getMessage());
           return;
        }
        tab_stock.setModel(model);
             int s=0;
           for(int j=0;j<tab_stock.getRowCount();j++){
              s+= Integer.parseInt(tab_stock.getValueAt(j,5).toString());
               res_stock.setText("Total: "+String.valueOf(s));
             
           }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_stock = new javax.swing.JTable();
        res_stock = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        des = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        prix = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        qte = new javax.swing.JTextField();
        modofoerstock = new javax.swing.JButton();
        suprimerstock = new javax.swing.JButton();
        chercherarticle = new javax.swing.JButton();
        cher = new javax.swing.JTextField();
        apercu = new javax.swing.JButton();
        datest = new datechooser.beans.DateChooserCombo();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Z-STock | Gestion de stock");
        setBackground(new java.awt.Color(37, 204, 247));

        jPanel1.setBackground(new java.awt.Color(37, 204, 247));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Etat de stock");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tab_stock.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tab_stock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Code Article", "Désignation", "Quantité", "Prix", "Montant"
            }
        ));
        tab_stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_stockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_stock);

        res_stock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ID");

        id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        code.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Code Article");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Désignation");

        des.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Prix");

        prix.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prix.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Quantité");

        qte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        modofoerstock.setBackground(new java.awt.Color(4, 139, 154));
        modofoerstock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modofoerstock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_image/modif (1).png"))); // NOI18N
        modofoerstock.setText("Modifier");
        modofoerstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modofoerstockActionPerformed(evt);
            }
        });

        suprimerstock.setBackground(new java.awt.Color(4, 139, 154));
        suprimerstock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        suprimerstock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_image/supprime (1).png"))); // NOI18N
        suprimerstock.setText("Supprimer");
        suprimerstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suprimerstockActionPerformed(evt);
            }
        });

        chercherarticle.setBackground(new java.awt.Color(4, 139, 154));
        chercherarticle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chercherarticle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_image/cc (1).jpg"))); // NOI18N
        chercherarticle.setText("Chercher");
        chercherarticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chercherarticleActionPerformed(evt);
            }
        });

        cher.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        apercu.setBackground(new java.awt.Color(4, 139, 154));
        apercu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        apercu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_image/apercu.png"))); // NOI18N
        apercu.setText("Aperçu");
        apercu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apercuActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_image/precedent (1).png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(res_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(316, 316, 316)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(datest, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(code)
                                    .addComponent(des)
                                    .addComponent(prix)
                                    .addComponent(qte, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(modofoerstock, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(suprimerstock))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(apercu, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chercherarticle, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(cher, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(res_stock, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(prix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modofoerstock, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suprimerstock, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apercu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chercherarticle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cher, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void tab_stockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_stockMouseClicked
       selectedrow=tab_stock.getSelectedRow();
        id.setText(model.getValueAt(tab_stock.getSelectedRow(),0).toString());
        code.setText(model.getValueAt(tab_stock.getSelectedRow(),1).toString());
        des.setText(model.getValueAt(tab_stock.getSelectedRow(),2).toString());
        qte.setText(model.getValueAt(tab_stock.getSelectedRow(),3).toString());
        prix.setText(model.getValueAt(tab_stock.getSelectedRow(),4).toString());
    }//GEN-LAST:event_tab_stockMouseClicked

    private void modofoerstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modofoerstockActionPerformed
        
        
     if(tab_stock.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this,"Selectionnée une ligne pour le modifier!!!!");
        }else{
         String req_update_stock="UPDATE stock SET code_art='"+code.getText()+"', desg_art='"+des.getText()+"', qte='"+Integer.parseInt(qte.getText())+"', prix_vente='"+Double.parseDouble(prix.getText())+"' WHERE id_stock='"+Integer.parseInt(id.getText())+"' ";
      
     try{
          if  (JOptionPane.showConfirmDialog(this,"voulez-vous modifier", "Verification!!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION)
            {
         stm=maconx.obtenircnx().createStatement();
         stm.executeUpdate(req_update_stock);
       //JOptionPane.showMessageDialog(this,"Modification réusite");
       id.setText("");
       des.setText("");
       code.setText("");
       prix.setText("");
       qte.setText("");
     }
     }
     catch(SQLException ex){
         JOptionPane.showMessageDialog(this,ex.getMessage());
         return;
     }
      }
                while (model.getRowCount()>0)
                    
                {
                    for(int i=0;i<model.getRowCount();i++)
                    {
                        model.removeRow(0);
                    }
                }
          affiche_stock();
    }//GEN-LAST:event_modofoerstockActionPerformed

    private void suprimerstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suprimerstockActionPerformed
       
        
      if(tab_stock.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this,"Selectionnée une ligne pour le supprimer!!!!");
        }else{
           String req_delete_stock="DELETE FROM stock WHERE id_stock='"+Integer.parseInt(id.getText())+"' ";
     try{ 
         if  (JOptionPane.showConfirmDialog(this,"voulez-vous supprimer", "Verification!!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION)
            {
         
         stm=maconx.obtenircnx().createStatement();
         stm.executeUpdate(req_delete_stock);
       //JOptionPane.showMessageDialog(this,"Suprission réusite");
       id.setText("");
       des.setText("");
       code.setText("");
       prix.setText("");
       qte.setText("");
            }
     }
     catch(SQLException ex){
         JOptionPane.showMessageDialog(this,ex.getMessage());
         return;
     }
     model.removeRow(selectedrow);
      }
                while (model.getRowCount()>0)
                    
                {
                    for(int i=0;i<model.getRowCount();i++)
                    {
                        model.removeRow(0);
                    }
                }
          affiche_stock();
    }//GEN-LAST:event_suprimerstockActionPerformed

    private void chercherarticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chercherarticleActionPerformed
               Boolean res=false;
        if (cher.getText().trim().equals("")){
                   JOptionPane.showMessageDialog(this, "Rien à chercher!!");
                   
               }else{
                  
         for(int i=0;i<tab_stock.getRowCount();i++)
        {
            if((tab_stock.getValueAt(i,1).equals(cher.getText()))||(tab_stock.getValueAt(i,2).equals(cher.getText())))
            {
                tab_stock.setRowSelectionInterval(i, i);
                res=true;
            }
          
        }
               
          }
        if(res==false){
              JOptionPane.showMessageDialog(this, "article introuvable ..");
              cher.setText("");
        }
    }//GEN-LAST:event_chercherarticleActionPerformed

    private void apercuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apercuActionPerformed
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String d=sdf.format(datest.getSelectedDate().getTime());
        
        apercu ap=new apercu();
        ap.dat_stock.setText(d);
        ap.setVisible(true);
        
    }//GEN-LAST:event_apercuActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
 acceuil a = new acceuil();
      a.setVisible(true); 
      this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionstock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionstock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionstock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionstock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestionstock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apercu;
    private javax.swing.JTextField cher;
    private javax.swing.JButton chercherarticle;
    private javax.swing.JTextField code;
    private datechooser.beans.DateChooserCombo datest;
    private javax.swing.JTextField des;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modofoerstock;
    private javax.swing.JTextField prix;
    private javax.swing.JTextField qte;
    private javax.swing.JLabel res_stock;
    private javax.swing.JButton suprimerstock;
    private javax.swing.JTable tab_stock;
    // End of variables declaration//GEN-END:variables
}
