/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monstock;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author YASSOU
 */
public class gestionfournisseur1 extends javax.swing.JFrame {
Statement stm,stm1;
    connexion maconx =new connexion();
    DefaultTableModel model;
    int selectedrow;
   
    /**
     * Creates new form gestionfournisseur1
     */
    public gestionfournisseur1() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        icon();
        model=(DefaultTableModel) tab_liv.getModel();
         listechauffeur();
    }
    
    void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo1.jpg")));
    }
    
    private void listechauffeur(){
          String req_affiche="select * from chauffeur";
         try{
              stm=maconx.obtenircnx().createStatement();
            ResultSet res=stm.executeQuery(req_affiche);
            while(res.next()){
               
               
                    String name=res.getString("nom")+" "+res.getString("prenom");
                    com.addItem(name);
            }
         }catch(SQLException ex){
             JOptionPane.showMessageDialog(this, ex.getMessage());
         }
         
    }
      public  void controle_champs(java.awt.event.KeyEvent evt)
        {
    char c=evt.getKeyChar();
        if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)){
            getToolkit().beep();
        evt.consume();
                }
          }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        date_liv = new datechooser.beans.DateChooserCombo();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_liv = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sec = new javax.swing.JTextField();
        com = new javax.swing.JComboBox<>();
        des = new javax.swing.JTextField();
        prix = new javax.swing.JTextField();
        qte = new javax.swing.JTextField();
        ajouterliv = new javax.swing.JButton();
        modifierliv = new javax.swing.JButton();
        supprimeruser = new javax.swing.JButton();
        nouvelfac = new javax.swing.JButton();
        imprimelivraison = new javax.swing.JButton();
        res = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Z-STock | Bon de sortie");

        jPanel1.setBackground(new java.awt.Color(37, 204, 247));

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Bon de Sortie");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tab_liv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tab_liv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Designation", "Prix", "Quantité", "Montant"
            }
        ));
        tab_liv.setRowHeight(25);
        tab_liv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_livMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_liv);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Secteur");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Commercial");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Désignation");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Prix");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Quantité");

        sec.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secActionPerformed(evt);
            }
        });

        com.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        com.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comActionPerformed(evt);
            }
        });

        des.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desActionPerformed(evt);
            }
        });
        des.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                desKeyReleased(evt);
            }
        });

        prix.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prixActionPerformed(evt);
            }
        });
        prix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                prixKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prixKeyTyped(evt);
            }
        });

        qte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        qte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qteActionPerformed(evt);
            }
        });
        qte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qteKeyTyped(evt);
            }
        });

        ajouterliv.setBackground(new java.awt.Color(4, 139, 154));
        ajouterliv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ajouterliv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monstock/enregistrer.png"))); // NOI18N
        ajouterliv.setText("Ajouter");
        ajouterliv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterlivActionPerformed(evt);
            }
        });

        modifierliv.setBackground(new java.awt.Color(4, 139, 154));
        modifierliv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modifierliv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_image/modif (1).png"))); // NOI18N
        modifierliv.setText("Modifier");
        modifierliv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierlivActionPerformed(evt);
            }
        });

        supprimeruser.setBackground(new java.awt.Color(4, 139, 154));
        supprimeruser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supprimeruser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_image/supprime (1).png"))); // NOI18N
        supprimeruser.setText("Supprimer");
        supprimeruser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimeruserActionPerformed(evt);
            }
        });

        nouvelfac.setBackground(new java.awt.Color(4, 139, 154));
        nouvelfac.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nouvelfac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_image/nouveau1.jpg"))); // NOI18N
        nouvelfac.setText("Nouvel facture");
        nouvelfac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouvelfacActionPerformed(evt);
            }
        });

        imprimelivraison.setBackground(new java.awt.Color(4, 139, 154));
        imprimelivraison.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        imprimelivraison.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_image/apercu.png"))); // NOI18N
        imprimelivraison.setText("Aperçu");
        imprimelivraison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimelivraisonActionPerformed(evt);
            }
        });

        res.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        res.setText("Total :");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_image/precedent (1).png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(366, 366, 366)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(date_liv, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sec)
                            .addComponent(des)
                            .addComponent(prix)
                            .addComponent(qte)
                            .addComponent(com, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(modifierliv, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ajouterliv, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(supprimeruser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(imprimelivraison, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(res, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(nouvelfac)))))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(date_liv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(com, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addGap(18, 18, 18)
                            .addComponent(prix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supprimeruser, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ajouterliv, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(imprimelivraison, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modifierliv, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(res, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(nouvelfac, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tab_livMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_livMouseClicked

        selectedrow=tab_liv.getSelectedRow();
        des.setText(model.getValueAt(tab_liv.getSelectedRow(),0).toString());
        prix.setText(model.getValueAt(tab_liv.getSelectedRow(),1).toString());
        qte.setText(model.getValueAt(tab_liv.getSelectedRow(),2).toString());

    }//GEN-LAST:event_tab_livMouseClicked

    private void secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secActionPerformed

    private void comActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comActionPerformed

    private void desActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desActionPerformed

    private void desKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_desKeyReleased

        String req="select prix_vente from stock where desg_art='"+des.getText()+"'";
        try{
            stm=maconx.obtenircnx().createStatement();
            ResultSet res=stm.executeQuery(req);
            if(res.next()){
                prix.setText(res.getString("prix_vente"));
                qte.requestFocus();
            }

        }catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
    }//GEN-LAST:event_desKeyReleased

    private void prixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prixActionPerformed

    private void qteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qteActionPerformed

    private void ajouterlivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterlivActionPerformed

        if((des.getText().equals(""))||(prix.getText().equals(""))||(qte.getText().equals(""))||(sec.getText().equals(""))){
            JOptionPane.showMessageDialog(this,"Remplir les champs");
        }
        else{

            int s=Integer.parseInt(prix.getText())*Integer.parseInt(qte.getText());
            model.addRow(new Object[] { des.getText(), prix.getText(),qte.getText(), s});
            des.setText("");
            prix.setText("");
            qte.setText("");
            des.requestFocus();

        }
        int s=0;
        for(int i=0;i<tab_liv.getRowCount();i++){
            s+= (Integer.parseInt(tab_liv.getValueAt(i,3).toString()));
            res.setText("Total :"+String.valueOf(s));

        }

    }//GEN-LAST:event_ajouterlivActionPerformed

    private void modifierlivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierlivActionPerformed
        if(tab_liv.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this,"Voulez vous selectionnée une ligne pour modifier");
            return;
        }
        else{
            if  (JOptionPane.showConfirmDialog(this,"voulez-vous modifier", "Verification!!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION)
            {

                model.setValueAt(des.getText(), tab_liv.getSelectedRow(),0);
                model.setValueAt(prix.getText(), tab_liv.getSelectedRow(),1);
                model.setValueAt(qte.getText(), tab_liv.getSelectedRow(),2);
                model.setValueAt(Integer.parseInt(qte.getText())*Integer.parseInt(prix.getText()), tab_liv.getSelectedRow(),3);

                des.setText("");
                prix.setText("");
                qte.setText("");

            }
        }
    }//GEN-LAST:event_modifierlivActionPerformed

    private void supprimeruserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimeruserActionPerformed
        if(tab_liv.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this,"tableau vide ou ligne n'est pas selectionée");
            return;
        } else{
            if  (JOptionPane.showConfirmDialog(this,"voulez-vous modifier", "Verification!!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION)
            {
                model.removeRow(selectedrow);
                des.setText("");
                prix.setText("");
                qte.setText("");
                des.requestFocus();
            }
        }
    }//GEN-LAST:event_supprimeruserActionPerformed

    private void nouvelfacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouvelfacActionPerformed

        if(tab_liv.getRowCount()==0){
            return;
        }
        else{
            while (model.getRowCount()>0)
            {
                for(int i=0;i<model.getRowCount();i++)
                {
                    model.removeRow(0);
                }
            }
            des.setText("");
            prix.setText("");
            qte.setText("");
            sec.setText("");
        }
    }//GEN-LAST:event_nouvelfacActionPerformed

    private void imprimelivraisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimelivraisonActionPerformed
      
        Object row[]=new Object[4];
        
        apercubonlivr ap=new apercubonlivr();
        
       DefaultTableModel model2 = (DefaultTableModel) ap.table_apercu_vente.getModel();
        
        
        
        if(tab_liv.getRowCount()==0){
            JOptionPane.showMessageDialog(this,"Tableau vide rien a imprimer!!!");
        }
        else{
      
        ap.date_vente.setText(date_liv.getText());
        ap.com.setText(com.getSelectedItem().toString());
        ap.sec.setText(sec.getText());
        ap.total.setText(res.getText());
        
        for(int i=0;i<tab_liv.getRowCount();i++)
        {
          
        row[0]=model.getValueAt(i, 0);
        row[1]=model.getValueAt(i, 2);
        row[2]=model.getValueAt(i, 1);
        row[3]=model.getValueAt(i, 3);
       
         model2.addRow(row);
        }
       
        ap.setVisible(true);   
    }       
    }//GEN-LAST:event_imprimelivraisonActionPerformed

    private void prixKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prixKeyPressed
        
    }//GEN-LAST:event_prixKeyPressed

    private void prixKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prixKeyTyped
controle_champs(evt);          // TODO add your handling code here:
    }//GEN-LAST:event_prixKeyTyped

    private void qteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qteKeyTyped
controle_champs(evt);          // TODO add your handling code here:
    }//GEN-LAST:event_qteKeyTyped

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        acceuil a = new acceuil();
      a.setVisible(true); 
      this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionfournisseur1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionfournisseur1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionfournisseur1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionfournisseur1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestionfournisseur1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterliv;
    private javax.swing.JComboBox<String> com;
    private datechooser.beans.DateChooserCombo date_liv;
    private javax.swing.JTextField des;
    private javax.swing.JButton imprimelivraison;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifierliv;
    private javax.swing.JButton nouvelfac;
    private javax.swing.JTextField prix;
    private javax.swing.JTextField qte;
    private javax.swing.JLabel res;
    private javax.swing.JTextField sec;
    private javax.swing.JButton supprimeruser;
    private javax.swing.JTable tab_liv;
    // End of variables declaration//GEN-END:variables
}
