/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monstock;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YASSOU
 */
public class gestionfournisseur extends javax.swing.JFrame {
 Statement stm,stm1;
    connexion maconx =new connexion();
    DefaultTableModel model;
    int selectedrow;
    /**
     * Creates new form gestionfournisseur
     */
    public gestionfournisseur() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
          model=(DefaultTableModel) tab_fournisseur.getModel();
          affiche();
             icon();
    }
    
     void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo1.jpg")));
    }
     
        public  void controle_champs(java.awt.event.KeyEvent evt)
        {
    char c=evt.getKeyChar();
        if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)){
            getToolkit().beep();
        evt.consume();
                }
          }
        
     public void affiche(){
         String req_affiche="select * from fournisseur";
         try{
              stm=maconx.obtenircnx().createStatement();
            ResultSet res=stm.executeQuery(req_affiche);
            while(res.next()){
                Vector v=new Vector();
                for(int i=0;i<model.getColumnCount();i++){
                     v.add(res.getInt("id"));
                    v.add(res.getString("nom_soc"));
                    v.add(res.getString("matricule"));
                    v.add(res.getString("adress"));
                    v.add(res.getString("tel"));
                    
                }
                 model.addRow(v);
            }
         }catch(SQLException ex){
             JOptionPane.showMessageDialog(this, ex.getMessage());
         }
     }
      
         
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_fournisseur = new javax.swing.JTable();
        nom = new javax.swing.JTextField();
        mf = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ajouterfour = new javax.swing.JButton();
        modifierfour = new javax.swing.JButton();
        supprimerfour = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        adress = new javax.swing.JTextField();
        chercherfour = new javax.swing.JButton();
        cher = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Z-STock | Gestion de fournisseur ");

        jPanel1.setBackground(new java.awt.Color(37, 204, 247));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion des fournisseurs");

        tab_fournisseur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nom société", "Matricule fiscal", "Adress", "Télephone"
            }
        ));
        tab_fournisseur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_fournisseurMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_fournisseur);

        nom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomFocusLost(evt);
            }
        });
        nom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nomMousePressed(evt);
            }
        });
        nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomKeyPressed(evt);
            }
        });

        mf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mfMousePressed(evt);
            }
        });
        mf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfActionPerformed(evt);
            }
        });

        tel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                telMousePressed(evt);
            }
        });
        tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nom de société");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Matricule fiscal");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Télephone");

        ajouterfour.setBackground(new java.awt.Color(4, 139, 154));
        ajouterfour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ajouterfour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_image/enregistrer.png"))); // NOI18N
        ajouterfour.setText("Ajouter");
        ajouterfour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterfourActionPerformed(evt);
            }
        });

        modifierfour.setBackground(new java.awt.Color(4, 139, 154));
        modifierfour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modifierfour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_image/modif (1).png"))); // NOI18N
        modifierfour.setText("Modifier");
        modifierfour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierfourActionPerformed(evt);
            }
        });

        supprimerfour.setBackground(new java.awt.Color(4, 139, 154));
        supprimerfour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supprimerfour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_image/supprime (1).png"))); // NOI18N
        supprimerfour.setText("Supprimer");
        supprimerfour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerfourActionPerformed(evt);
            }
        });

        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Adress");

        adress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        adress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adressMousePressed(evt);
            }
        });

        chercherfour.setBackground(new java.awt.Color(4, 139, 154));
        chercherfour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chercherfour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_image/cc (1).jpg"))); // NOI18N
        chercherfour.setText("Chercher");
        chercherfour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chercherfourActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ID");

        id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_image/precedent (1).png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(mf, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                .addComponent(nom)
                                .addComponent(tel)
                                .addComponent(adress))
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chercherfour, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ajouterfour, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(modifierfour, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cher, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)))
                        .addComponent(supprimerfour))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(353, 353, 353)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(494, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(adress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ajouterfour, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modifierfour, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supprimerfour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chercherfour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chercherfourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chercherfourActionPerformed

        if (cher.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"champs a chercher est vide !!");
        }else{
            for(int i=0;i<tab_fournisseur.getRowCount();i++)
            {
                if(tab_fournisseur.getValueAt(i,0).equals(cher.getText()))
                {
                    tab_fournisseur.setRowSelectionInterval(i, i);
                }
                else{
                    JOptionPane.showMessageDialog(this,"recherche introvable !!");
                }
            }
        }
    }//GEN-LAST:event_chercherfourActionPerformed

    private void adressMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adressMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_adressMousePressed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void supprimerfourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerfourActionPerformed

        if(tab_fournisseur.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this,"Voulez vous selectionnée un article pour supprimer");
            return;
        }
        else{
            String requete="DELETE FROM fournisseur where id='"+Integer.parseInt(id.getText())+"'";
            try{

                stm=maconx.obtenircnx().createStatement();

                if  (JOptionPane.showConfirmDialog(this,"voulez-vous supprimer", "Verification!!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION)
                {
                    stm.executeUpdate(requete);
                    model.removeRow(selectedrow);

                }
            }catch (SQLException ex) {
                JOptionPane.showConfirmDialog(this, ex.getMessage());
            }

        }
        id.setText("");
        nom.setText("");
        mf.setText("");
        adress.setText("");

        tel.setText("");
    }//GEN-LAST:event_supprimerfourActionPerformed

    private void modifierfourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierfourActionPerformed

        if(tab_fournisseur.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this,"Voulez vous selectionnée une ligne pour modifier");
            return;
        }
        else{
            String req_update_user="UPDATE fournisseur SET nom_soc='"+nom.getText()+"', matricule='"+mf.getText()+"', adress='"+adress.getText()+"', tel='"+tel.getText()+"' where nom_soc='"+Integer.parseInt(id.getText())+"'  ";
            try{
                if  (JOptionPane.showConfirmDialog(this,"voulez-vous modifier", "Verification!!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION)
                {
                    stm=maconx.obtenircnx().createStatement();
                    stm.executeUpdate(req_update_user);

                    model.setValueAt(id.getText(), tab_fournisseur.getSelectedRow(),0);
                    model.setValueAt(nom.getText(), tab_fournisseur.getSelectedRow(),1);
                    model.setValueAt(mf.getText(), tab_fournisseur.getSelectedRow(),2);
                    model.setValueAt(adress.getText(), tab_fournisseur.getSelectedRow(),3);
                    model.setValueAt(tel.getText(), tab_fournisseur.getSelectedRow(),4);
                    id.setText("");
                    nom.setText("");
                    mf.setText("");
                    adress.setText("");
                    tel.setText("");
                }
            }catch (SQLException ex){
                System.out.println(ex);
            }

        }
    }//GEN-LAST:event_modifierfourActionPerformed

    private void ajouterfourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterfourActionPerformed

        if((nom.getText().equals(""))||(mf.getText().equals(""))||(adress.getText().equals(""))||(tel.getText().equals(""))){
            JOptionPane.showMessageDialog(this, "Champs vide!");
        }
        else{
            String req_user="INSERT INTO fournisseur (nom_soc, matricule, adress, tel) VALUES ('"+nom.getText()+"','"+mf.getText()+"', '"+adress.getText()+"','"+tel.getText()+"')";
            String req_sel_user="SELECT * FROM fournisseur WHERE nom_soc='"+nom.getText()+"' AND matricule='"+mf.getText()+"'";

            try{
                stm1=maconx.obtenircnx().createStatement();
                stm=maconx.obtenircnx().createStatement();
                ResultSet res=stm.executeQuery(req_sel_user);

                if(res.next()){
                    JOptionPane.showMessageDialog(this, "Ce nom est deja existe choisir un notre!!!");
                    nom.setText("");
                    mf.setText("");
                    adress.setText("");

                    tel.setText("");

                }

                else{
                    stm1.executeUpdate(req_user);
                    JOptionPane.showMessageDialog(this, "Enregistrement reussite");
                    // model.addRow(new Object[] {nom.getText(), mf.getText(), adress.getText(), tel.getText()});
                    while (model.getRowCount()>0)
                    {
                        for(int i=0;i<model.getRowCount();i++)
                        {
                            model.removeRow(0);
                        }
                    }
                    affiche();

                    nom.setText("");
                    mf.setText("");
                    adress.setText("");
                    tel.setText("");
                }

            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(null,ex.getMessage());
                return;
            }
        }
    }//GEN-LAST:event_ajouterfourActionPerformed

    private void telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telKeyTyped
        controle_champs(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_telKeyTyped

    private void telKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_telKeyPressed

    private void telMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_telMousePressed

    private void mfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mfActionPerformed

    private void mfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mfMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mfMousePressed

    private void nomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomKeyPressed

    private void nomMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomMousePressed

    private void nomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_nomFocusLost

    private void tab_fournisseurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_fournisseurMouseClicked

        selectedrow=tab_fournisseur.getSelectedRow();
        id.setText(model.getValueAt(tab_fournisseur.getSelectedRow(),0).toString());
        nom.setText(model.getValueAt(tab_fournisseur.getSelectedRow(),1).toString());
        mf.setText(model.getValueAt(tab_fournisseur.getSelectedRow(),2).toString());
        adress.setText(model.getValueAt(tab_fournisseur.getSelectedRow(),3).toString());
        tel.setText(model.getValueAt(tab_fournisseur.getSelectedRow(),4).toString());
    }//GEN-LAST:event_tab_fournisseurMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        acceuil a = new acceuil();
      a.setVisible(true); 
      this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionfournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionfournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionfournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionfournisseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestionfournisseur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adress;
    private javax.swing.JButton ajouterfour;
    private javax.swing.JTextField cher;
    private javax.swing.JButton chercherfour;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mf;
    private javax.swing.JButton modifierfour;
    private javax.swing.JTextField nom;
    private javax.swing.JButton supprimerfour;
    private javax.swing.JTable tab_fournisseur;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables
}
