/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monstock;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YASSOU
 */
public class gestiondepense extends javax.swing.JFrame {

    Statement stm,stm1;
    connexion maconx =new connexion();
    DefaultTableModel model;
    int selectedrow;
    /**
     * Creates new form gestiondepense
     */
    public gestiondepense() {
        initComponents();
     this.setLocationRelativeTo(null);
        setResizable(false);
          model=(DefaultTableModel) tab_dep.getModel();
             icon();
               listechauffeur();
               
    }

     void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo1.jpg")));
    }
    
     public  void controle_champs(java.awt.event.KeyEvent evt)
        {
    char c=evt.getKeyChar();
        if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)){
            getToolkit().beep();
        evt.consume();
                }
          }

      private void listechauffeur(){
          String req_affiche="select * from chauffeur";
         try{
              stm=maconx.obtenircnx().createStatement();
            ResultSet res=stm.executeQuery(req_affiche);
            while(res.next()){
               
               
                    String name=res.getString("nom")+" "+res.getString("prenom");
                    com.addItem(name);
            }
         }catch(SQLException ex){
             JOptionPane.showMessageDialog(this, ex.getMessage());
         }
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_dep = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sec = new javax.swing.JTextField();
        com = new javax.swing.JComboBox<>();
        des = new javax.swing.JTextField();
        mon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ajouterdep = new javax.swing.JButton();
        modifierdep = new javax.swing.JButton();
        supprimerdep = new javax.swing.JButton();
        chid = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        res = new javax.swing.JLabel();
        date_dep = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Z-STock | Gestion des dépenses");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(37, 204, 247));

        jPanel1.setBackground(new java.awt.Color(37, 204, 247));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion des dépenses");

        tab_dep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tab_dep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Chauffeur", "Secteur", "Description", "Date", "Montant"
            }
        ));
        tab_dep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_depMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_dep);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Chauffeur");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Secteur");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Description");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Montant");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Date");

        sec.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        com.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        des.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        mon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monActionPerformed(evt);
            }
        });
        mon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                monKeyTyped(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\YASSOU\\Desktop\\developpement\\imagegestion_stock\\precedent (1).png")); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        ajouterdep.setBackground(new java.awt.Color(4, 139, 154));
        ajouterdep.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ajouterdep.setIcon(new javax.swing.ImageIcon("C:\\Users\\YASSOU\\Desktop\\developpement\\application gestion des produits\\gestion des produit\\src\\gestion\\des\\produit\\icon\\ajouter.png")); // NOI18N
        ajouterdep.setText("Ajouter");
        ajouterdep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterdepActionPerformed(evt);
            }
        });

        modifierdep.setBackground(new java.awt.Color(4, 139, 154));
        modifierdep.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modifierdep.setIcon(new javax.swing.ImageIcon("C:\\Users\\YASSOU\\Desktop\\developpement\\imagegestion_stock\\modif (1).png")); // NOI18N
        modifierdep.setText("Modifier");
        modifierdep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierdepActionPerformed(evt);
            }
        });

        supprimerdep.setBackground(new java.awt.Color(4, 139, 154));
        supprimerdep.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supprimerdep.setIcon(new javax.swing.ImageIcon("C:\\Users\\YASSOU\\Desktop\\developpement\\imagegestion_stock\\supprime (1).png")); // NOI18N
        supprimerdep.setText("Supprimer");
        supprimerdep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerdepActionPerformed(evt);
            }
        });

        chid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("ID");

        res.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        res.setText("Total :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(sec, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(com, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(des)
                                    .addComponent(mon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(date_dep, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(modifierdep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(supprimerdep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ajouterdep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chid, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(res, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(160, 160, 160))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 145, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(379, 379, 379)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(com, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modifierdep, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(mon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(date_dep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(29, 29, 29))
                            .addComponent(supprimerdep, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(res)
                        .addGap(18, 18, 18)
                        .addComponent(ajouterdep, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void ajouterdepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterdepActionPerformed
  
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy/MM/dd");
        String date=sdf.format(date_dep.getSelectedDate().getTime());
         chid.setText("");
        if((des.getText().equals(""))||(sec.getText().equals(""))||(mon.getText().equals(""))){
            JOptionPane.showMessageDialog(this, "Champs vide!");
            return;
        }
        else{
           
            String req_dep="INSERT INTO depense (chauffeur, secteur, date,description, montant) VALUES ('"+com.getSelectedItem()+"','"+sec.getText()+"','"+date+"' , '"+des.getText()+"', '"+Integer.parseInt(mon.getText())+"')";
            try{

                stm=maconx.obtenircnx().createStatement();
                stm.executeUpdate(req_dep);
                JOptionPane.showMessageDialog(this, "Enregistrement reussite");
                model.addRow(new Object[] {com.getSelectedItem(), sec.getText(), des.getText(),date, mon.getText()});
                des.setText("");
                sec.setText("");

                mon.setText("");
            }

            catch(SQLException ex){
                JOptionPane.showMessageDialog(null,ex.getMessage());
                return;
            }
             com.setSelectedItem("--");
            sec.setText("");
            des.setText("");
            mon.setText("");
        }
        int s=0;
        for(int i=0;i<tab_dep.getRowCount();i++){
            s+= (Integer.parseInt(tab_dep.getValueAt(i,4).toString()));
            res.setText("Total :"+String.valueOf(s));
        }
    }//GEN-LAST:event_ajouterdepActionPerformed

    private void monKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monKeyTyped
             controle_champs(evt);            
    }//GEN-LAST:event_monKeyTyped

    private void tab_depMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_depMouseClicked
       
         selectedrow=tab_dep.getSelectedRow();
         
         com.setSelectedItem(model.getValueAt(selectedrow,0).toString());
        sec.setText(model.getValueAt(selectedrow,1).toString());
        des.setText(model.getValueAt(selectedrow,2).toString());
        mon.setText(model.getValueAt(selectedrow,4).toString());
         
         try{
              //Date sdf= new SimpleDateFormat("yyyy/dd/MM").parse((String)model.getValueAt(tab_dep.getSelectedRow(),3));
              String selectid="select id from depense where chauffeur='"+model.getValueAt(selectedrow,0).toString()+"' and secteur='"+model.getValueAt(selectedrow,1).toString()+"' and date='"+model.getValueAt(selectedrow,3).toString()+"' and description='"+model.getValueAt(selectedrow,2).toString()+"' ";
             stm1=maconx.obtenircnx().createStatement();
             
                 ResultSet res=stm1.executeQuery(selectid);
                 while(res.next()){
                     
                     int nid=res.getInt("id");
                    
        
        
         chid.setText(Integer.toString(nid));
                            }
         
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }
    }//GEN-LAST:event_tab_depMouseClicked

    private void monActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monActionPerformed

    private void modifierdepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierdepActionPerformed
          
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy/MM/dd");
        String date=sdf.format(date_dep.getSelectedDate().getTime());
        
        if(tab_dep.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this,"Voulez vous selectionnée une ligne pour modifier");
            return;
        }
        else{
            String req_update_dep="UPDATE depense SET chauffeur='"+com.getSelectedItem()+"', secteur='"+sec.getText()+"', date='"+date+"' , description='"+des.getText()+"', montant='"+mon.getText()+"' where id='"+Integer.parseInt(chid.getText())+"' ";
            try{
                if  (JOptionPane.showConfirmDialog(this,"voulez-vous modifier", "Verification!!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION)
                {
                    stm=maconx.obtenircnx().createStatement();
                    stm.executeUpdate(req_update_dep);
                   
                   
                }
                    model.setValueAt(com.getSelectedItem(), tab_dep.getSelectedRow(),0);
                    model.setValueAt(sec.getText(), tab_dep.getSelectedRow(),1);   
                    model.setValueAt(des.getText(), tab_dep.getSelectedRow(),2);
                    model.setValueAt(date, tab_dep.getSelectedRow(),3);
                    model.setValueAt(mon.getText(), tab_dep.getSelectedRow(),4);
                     
            }catch (SQLException ex){
             
                JOptionPane.showMessageDialog(this, ex);
                return;
            }
             com.setSelectedItem("--");
            sec.setText("");
            des.setText("");
            mon.setText("");
            
        }
         int s=0;
        for(int i=0;i<tab_dep.getRowCount();i++){
            s+= (Integer.parseInt(tab_dep.getValueAt(i,4).toString()));
            res.setText("Total :"+String.valueOf(s));
        }

    }//GEN-LAST:event_modifierdepActionPerformed

    private void supprimerdepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerdepActionPerformed

        SimpleDateFormat sdf=new SimpleDateFormat("yyyy/MM/dd");
        String date=sdf.format(date_dep.getSelectedDate().getTime());
     
        if(tab_dep.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this,"Voulez vous selectionnée un article pour supprimer");
            return;
        }
        else{

            String requete="DELETE FROM depense where id='"+Integer.parseInt(chid.getText())+"' ";
            try{

                stm=maconx.obtenircnx().createStatement();
                
             if  (JOptionPane.showConfirmDialog(this,"voulez-vous supprimer", "Verification!!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION)
                {
                    stm.executeUpdate(requete);
                    model.removeRow(selectedrow);
                       chid.setText("");
                }
            }catch (SQLException ex) {
                System.out.println(ex);
            }
            com.setSelectedItem("--");
            sec.setText("");
            des.setText("");
            mon.setText("");
        }
        int s=0;
        for(int i=0;i<tab_dep.getRowCount();i++){
            s+= (Integer.parseInt(tab_dep.getValueAt(i,4).toString()));
            res.setText("Total :"+String.valueOf(s));
        }
    }//GEN-LAST:event_supprimerdepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestiondepense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestiondepense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestiondepense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestiondepense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestiondepense().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterdep;
    private javax.swing.JLabel chid;
    private javax.swing.JComboBox<String> com;
    private datechooser.beans.DateChooserCombo date_dep;
    private javax.swing.JTextField des;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifierdep;
    private javax.swing.JTextField mon;
    private javax.swing.JLabel res;
    private javax.swing.JTextField sec;
    private javax.swing.JButton supprimerdep;
    private javax.swing.JTable tab_dep;
    // End of variables declaration//GEN-END:variables
}
