/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monstock;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YASSOU
 */
public class gestionvente extends javax.swing.JFrame {

      Statement stm,stm1;
    connexion maconx =new connexion();
    DefaultTableModel model;
    int selectedrow;
      int reste;
    /**
     * Creates new form gestionvente
     */
    public gestionvente() {
        initComponents();
              this.setLocationRelativeTo(null);
        setResizable(false);
          model=(DefaultTableModel) tab_vente.getModel();
         listechauffeur();
             icon();
    }
    
    
    

    void icon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo1.jpg")));
    }
    
     public  void controle_champs(java.awt.event.KeyEvent evt)
        {
    char c=evt.getKeyChar();
        if(!(Character.isDigit(c))||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)){
            getToolkit().beep();
        evt.consume();
                }
          }
    private void listechauffeur(){
          String req_affiche="select * from chauffeur";
         try{
              stm=maconx.obtenircnx().createStatement();
            ResultSet res=stm.executeQuery(req_affiche);
            while(res.next()){
               
               
                    String name=res.getString("nom")+" "+res.getString("prenom");
                    chauf.addItem(name);
            }
         }catch(SQLException ex){
             JOptionPane.showMessageDialog(this, ex.getMessage());
         }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        date_vente = new datechooser.beans.DateChooserCombo();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        secteur = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        chauf = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        desgvente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        prix_vente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        qte_vente = new javax.swing.JTextField();
        ajoutvente = new javax.swing.JButton();
        modifiervente = new javax.swing.JButton();
        apercuvente = new javax.swing.JButton();
        supprimervente = new javax.swing.JButton();
        nouvelvente = new javax.swing.JButton();
        enregistrer_valider = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_vente = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        res_vente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Z-STock | Gestion de vente");

        jPanel1.setBackground(new java.awt.Color(37, 204, 247));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\YASSOU\\Desktop\\developpement\\imagegestion_stock\\precedent (1).png")); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Facture N°");

        num.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        num.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jPanel2.setBackground(new java.awt.Color(37, 204, 247));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Secteur");

        secteur.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Chauffeur");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Code article");

        code.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codeKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Désignation");

        desgvente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Prix ");

        prix_vente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        prix_vente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prix_venteKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Quantité");

        qte_vente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        qte_vente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qte_venteKeyTyped(evt);
            }
        });

        ajoutvente.setBackground(new java.awt.Color(4, 139, 154));
        ajoutvente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ajoutvente.setIcon(new javax.swing.ImageIcon("C:\\Users\\YASSOU\\Desktop\\developpement\\application gestion des produits\\gestion des produit\\src\\gestion\\des\\produit\\icon\\noveau.png")); // NOI18N
        ajoutvente.setText("Ajouter");
        ajoutvente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutventeActionPerformed(evt);
            }
        });

        modifiervente.setBackground(new java.awt.Color(4, 139, 154));
        modifiervente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modifiervente.setIcon(new javax.swing.ImageIcon("C:\\Users\\YASSOU\\Desktop\\developpement\\imagegestion_stock\\modif (1).png")); // NOI18N
        modifiervente.setText("Modifier");
        modifiervente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierventeActionPerformed(evt);
            }
        });

        apercuvente.setBackground(new java.awt.Color(4, 139, 154));
        apercuvente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        apercuvente.setIcon(new javax.swing.ImageIcon("C:\\Users\\YASSOU\\Desktop\\developpement\\imagegestion_stock\\apercu.png")); // NOI18N
        apercuvente.setText("Aperçu");
        apercuvente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apercuventeActionPerformed(evt);
            }
        });

        supprimervente.setBackground(new java.awt.Color(4, 139, 154));
        supprimervente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supprimervente.setIcon(new javax.swing.ImageIcon("C:\\Users\\YASSOU\\Desktop\\developpement\\imagegestion_stock\\supprime (1).png")); // NOI18N
        supprimervente.setText("Supprimer");
        supprimervente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerventeActionPerformed(evt);
            }
        });

        nouvelvente.setBackground(new java.awt.Color(4, 139, 154));
        nouvelvente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nouvelvente.setIcon(new javax.swing.ImageIcon("C:\\Users\\YASSOU\\Desktop\\developpement\\application gestion des produits\\gestion des produit\\src\\gestion\\des\\produit\\icon\\noveau.png")); // NOI18N
        nouvelvente.setText("Nouvelle  ");
        nouvelvente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouvelventeActionPerformed(evt);
            }
        });

        enregistrer_valider.setBackground(new java.awt.Color(4, 139, 154));
        enregistrer_valider.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enregistrer_valider.setIcon(new javax.swing.ImageIcon("C:\\Users\\YASSOU\\Desktop\\developpement\\imagegestion_stock\\enregistrer.png")); // NOI18N
        enregistrer_valider.setText("Enregistrer");
        enregistrer_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrer_validerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(39, 39, 39)
                                .addComponent(qte_vente))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(69, 69, 69)
                                .addComponent(prix_vente))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(desgvente))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(46, 46, 46)
                                .addComponent(secteur))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(code)
                                    .addComponent(chauf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(supprimervente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ajoutvente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nouvelvente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(enregistrer_valider, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(modifiervente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apercuvente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 26, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(secteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(chauf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(desgvente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(prix_vente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(qte_vente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajoutvente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enregistrer_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supprimervente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modifiervente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nouvelvente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apercuvente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        tab_vente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code Article", "Désignation", "Prix", "Quantité", "Total"
            }
        ));
        tab_vente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_venteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_vente);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Total :");

        res_vente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(327, 327, 327)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(date_vente, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(res_vente, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(date_vente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(res_vente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        
        if (tab_vente.getRowCount()==0){
             this.dispose();
        }else{
  if  (JOptionPane.showConfirmDialog(this,"voulez-vous quiter!! facture n'est pas enregistrer...", "Verification!!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION)
                {

                  this.dispose();
  }      
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void ajoutventeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutventeActionPerformed
        Statement update_stock;
        if((num.getText().equals(""))||(code.getText().equals(""))||(desgvente.getText().equals(""))||(prix_vente.getText().equals(""))||(qte_vente.getText().equals(""))||(secteur.getText().equals(""))){
            JOptionPane.showMessageDialog(this,"Remplir les Champs");
            return;
        }
        else{
               String rq_stock="SELECT  qte  FROM stock where code_art='"+code.getText()+"' and desg_art='"+desgvente.getText()+"' ";  
                  try{
                     update_stock=maconx.obtenircnx().createStatement(); 
                 stm1=maconx.obtenircnx().createStatement();
                 ResultSet res_stock=stm1.executeQuery(rq_stock);
                 
                 while(res_stock.next()){
                     
                     if(res_stock.getInt("qte")< Integer.parseInt(qte_vente.getText())){
                          JOptionPane.showMessageDialog(this, "Il vous reste "+res_stock.getInt("qte"));
                          return;
                     }else{
                          model.addRow(new Object[]{code.getText(), desgvente.getText(), prix_vente.getText(), qte_vente.getText(), (Integer.parseInt(prix_vente.getText())*Integer.parseInt(qte_vente.getText()))});
           
                            code.setText("");
                           desgvente.setText("");
                           prix_vente.setText("");
                           qte_vente.setText("");
                           code.requestFocus();
           
                                 int s=0;
           for(int j=0;j<tab_vente.getRowCount();j++){
              s+= Integer.parseInt(tab_vente.getValueAt(j,4).toString());
              res_vente.setText(String.valueOf(s));
           }
                     }
                 
                 
                 } 
             }catch(SQLException ex){
                 JOptionPane.showMessageDialog(this, ex.getMessage());
             } 
          
        }
    }//GEN-LAST:event_ajoutventeActionPerformed

    private void codeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeKeyReleased
 
        String req="select * from stock where code_art='"+code.getText()+"'";
       try{
           stm=maconx.obtenircnx().createStatement();
            ResultSet res=stm.executeQuery(req);
            if(res.next()){
               
                desgvente.setText(res.getString("desg_art"));
                prix_vente.setText(res.getString("prix_vente"));
                qte_vente.requestFocus();
                
            }
           
       }catch(SQLException ex)
       {
           JOptionPane.showMessageDialog(this,ex.getMessage());
       }
               // TODO add your handling code here:
    }//GEN-LAST:event_codeKeyReleased

    private void codeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeKeyTyped
             
    }//GEN-LAST:event_codeKeyTyped

    private void prix_venteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prix_venteKeyTyped
         controle_champs(evt);            
    }//GEN-LAST:event_prix_venteKeyTyped

    private void qte_venteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qte_venteKeyTyped
  controle_champs(evt);                    // TODO add your handling code here:
    }//GEN-LAST:event_qte_venteKeyTyped

    private void nouvelventeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouvelventeActionPerformed
  if (tab_vente.getRowCount()==0){
             return;
        }else{
  if  (JOptionPane.showConfirmDialog(this,"Facture n'est pas enregistrer... Voulez-vous annuler", "Verification!!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION)
                {

         while (model.getRowCount()>0)
                {
                    for(int i=0;i<model.getRowCount();i++)
                    {
                        model.removeRow(0);
                    }
                }
         num.setText("");
         secteur.setText(""); 
         chauf.setSelectedItem(null);  
        code.setText("");
        desgvente.setText("");
        prix_vente.setText("");
        qte_vente.setText("");
        res_vente.setText("");
                }
  }
    }//GEN-LAST:event_nouvelventeActionPerformed

    private void tab_venteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_venteMouseClicked
         
        selectedrow=tab_vente.getSelectedRow();
       
         code.setText(model.getValueAt(tab_vente.getSelectedRow(),0).toString());
        desgvente.setText(model.getValueAt(tab_vente.getSelectedRow(),1).toString());
        prix_vente.setText(model.getValueAt(tab_vente.getSelectedRow(),2).toString());
          qte_vente.setText(model.getValueAt(tab_vente.getSelectedRow(),3).toString());
         
       
    }//GEN-LAST:event_tab_venteMouseClicked

    private void supprimerventeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerventeActionPerformed
       
        
        if(tab_vente.getSelectedRow()==-1){
            
            JOptionPane.showMessageDialog(this,"Voulez vous selectionnée un article pour supprimer");
            return;
        }
         else{ 
         if  (JOptionPane.showConfirmDialog(this,"voulez-vous supprimer", "Verification!!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION)
      {
       
        model.removeRow(selectedrow);
          double s=0;
           for(int j=0;j<tab_vente.getRowCount();j++){
              s+= Double.parseDouble(tab_vente.getValueAt(j,4).toString());
              res_vente.setText(String.valueOf(s));
           }
           
           code.setText("");
           desgvente.setText("");
           prix_vente.setText("");
           qte_vente.setText("");
           code.requestFocus(); 
           
         }
        }
    }//GEN-LAST:event_supprimerventeActionPerformed

    private void modifierventeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierventeActionPerformed
      
         int somme;
          if(tab_vente.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this,"Voulez vous selectionnée un article pour modifier");
        }
         else{
               if  (JOptionPane.showConfirmDialog(this,"voulez-vous modifier", "Verification!!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION)
      {
         somme=(int) (Double.parseDouble(qte_vente.getText())*Double.parseDouble(prix_vente.getText()));
        
         model.setValueAt(code.getText(), tab_vente.getSelectedRow(),0);
                 model.setValueAt(desgvente.getText(), tab_vente.getSelectedRow(),1);
                 model.setValueAt(prix_vente.getText(), tab_vente.getSelectedRow(),2);
                 model.setValueAt(qte_vente.getText(), tab_vente.getSelectedRow(),3);
                 model.setValueAt(String.valueOf(somme), tab_vente.getSelectedRow(),4);
               
          code.setText("");
           desgvente.setText("");
           prix_vente.setText("");
           qte_vente.setText("");
           code.requestFocus();
             code.requestFocus();
                  
      }
              
          }
         
                 int s=0;
           for(int j=0;j<tab_vente.getRowCount();j++){
              s+= Integer.parseInt(tab_vente.getValueAt(j,4).toString());
              res_vente.setText(String.valueOf(s));
           }
           
    }//GEN-LAST:event_modifierventeActionPerformed

    private void apercuventeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apercuventeActionPerformed

        Object row[]=new Object[4];
        
        apercu_vente ap=new apercu_vente();
        
       DefaultTableModel model2 = (DefaultTableModel) ap.table_apercu_vente.getModel();
        
        
        
        if(tab_vente.getRowCount()==0){
            JOptionPane.showMessageDialog(this,"Tableau vide rien a imprimer!!!");
        }
        else{
        ap.facture.setText(num.getText());
        ap.date_vente.setText(date_vente.getText());
        ap.com.setText(chauf.getSelectedItem().toString());
        ap.sec.setText(secteur.getText());
        ap.total.setText(res_vente.getText());
        
        for(int i=0;i<tab_vente.getRowCount();i++)
        {
          
        row[0]=model.getValueAt(i, 1);
        row[1]=model.getValueAt(i, 2);
        row[2]=model.getValueAt(i, 3);
        row[3]=model.getValueAt(i, 4);
       
         model2.addRow(row);
        }
       
        ap.setVisible(true);   
    }       
        
    }//GEN-LAST:event_apercuventeActionPerformed

    private void enregistrer_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrer_validerActionPerformed

        SimpleDateFormat sdf=new SimpleDateFormat("yyyy/MM/dd");
        String date=sdf.format(date_vente.getSelectedDate().getTime());
        
        Statement stm_stock,stm_update;
        
         if (tab_vente.getRowCount()==0) {
                JOptionPane.showMessageDialog(null, "Facture vide !!!");
            return;
        }else{
          if  (JOptionPane.showConfirmDialog(this,"voulez-vous Enregistrer!! ..", "Verification!!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION)
                {    
          for(int i=0;i<tab_vente.getRowCount(); i++){
          
             String c=(tab_vente.getValueAt(i,0).toString());
              String d=(tab_vente.getValueAt(i,1).toString());
               String p=(tab_vente.getValueAt(i,2).toString());
                String q=(tab_vente.getValueAt(i,3).toString());
                 String m=(tab_vente.getValueAt(i,4).toString());
                 
 String requete= "INSERT INTO vente (num_facture, date_vente, code_art, desg, prix, qte_vente, montant, commercial, secteur) VALUES ('"+num.getText()+"', '"+date+"', '"+c+"','"+d+"', '"+Double.parseDouble(p)+"', '"+Double.parseDouble(q)+"', '"+Double.parseDouble(m)+"',  '"+chauf.getSelectedItem()+"', '"+secteur.getText()+"')";
             try{
                 stm=maconx.obtenircnx().createStatement();
                 stm.executeUpdate(requete);
                 
             }catch(SQLException ex){
                 JOptionPane.showMessageDialog(this, ex.getMessage());
             }               
        }
          // update stock
           
            for(int j=0;j<tab_vente.getRowCount();j++){
                
                 String c=(tab_vente.getValueAt(j,0).toString());
                  String d=(tab_vente.getValueAt(j,1).toString());
                  String p=(tab_vente.getValueAt(j,2).toString());
                 String q=(tab_vente.getValueAt(j,3).toString());
                 
              String rq_stock="SELECT  qte  FROM stock where code_art='"+c+"'";
              try{
                  stm_stock=maconx.obtenircnx().createStatement();
                  
                    ResultSet res_stock=stm_stock.executeQuery(rq_stock);
                    
                     if(res_stock.next()){
                       int stock=res_stock.getInt("qte")-(Integer.parseInt(q));
       String req_update_stock="UPDATE stock SET  desg_art='"+d+"', qte='"+stock+"', prix_vente='"+p+"' WHERE code_art='"+c+"' ";
             try{
                 stm_update=maconx.obtenircnx().createStatement();
                 stm_update.executeUpdate(req_update_stock);
                 
                  
             }catch(SQLException ex){
                  JOptionPane.showMessageDialog(this, ex.getMessage());
                  
              }
                  }
              }catch(SQLException ex){
                  JOptionPane.showMessageDialog(this, ex.getMessage());
                  
              }
              
            }
            JOptionPane.showMessageDialog(this,"Enregistrement réussiste..");
               num.setText("");
            code.setText("");
           desgvente.setText("");
           prix_vente.setText("");
           qte_vente.setText("");
           res_vente.setText("");
           code.requestFocus();
           
          //update stock
          }
         
          
        while (model.getRowCount()>0)
                {
                    for(int i=0;i<model.getRowCount();i++)
                    {
                        model.removeRow(0);
                    }
                }
           
          
                }
         
    }//GEN-LAST:event_enregistrer_validerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionvente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionvente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionvente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionvente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestionvente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajoutvente;
    private javax.swing.JButton apercuvente;
    private javax.swing.JComboBox<String> chauf;
    private javax.swing.JTextField code;
    private datechooser.beans.DateChooserCombo date_vente;
    private javax.swing.JTextField desgvente;
    private javax.swing.JButton enregistrer_valider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifiervente;
    private javax.swing.JButton nouvelvente;
    private javax.swing.JTextField num;
    private javax.swing.JTextField prix_vente;
    private javax.swing.JTextField qte_vente;
    private javax.swing.JLabel res_vente;
    private javax.swing.JTextField secteur;
    private javax.swing.JButton supprimervente;
    private javax.swing.JTable tab_vente;
    // End of variables declaration//GEN-END:variables
}
