/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monstock;

import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YASSOU
 */
public class gestionfinanciere extends javax.swing.JFrame {
Statement stm, stm1;
    connexion maconx = new connexion();
    
    DefaultTableModel model;
    
      int selectedrow;
    /**
     * Creates new form gestionfinanciere
     */
    public gestionfinanciere() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        this.setLocationRelativeTo(null);
        setResizable(false);
        icon();
        listechauffeur();
      model=(DefaultTableModel) table_reche_vente.getModel();
       // model = (DefaultTableModel) tab_achat.getModel();
    }
    
    void icon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo1.jpg")));
     }
 
  private void listechauffeur(){
          String req_affiche="select * from chauffeur";
         try{
              stm=maconx.obtenircnx().createStatement();
            ResultSet res=stm.executeQuery(req_affiche);
            while(res.next()){
               
               
                    String name=res.getString("nom")+" "+res.getString("prenom");
                    chauf.addItem(name);
            }
         }catch(SQLException ex){
             JOptionPane.showMessageDialog(this, ex.getMessage());
         }
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        chauf = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        date1 = new datechooser.beans.DateChooserCombo();
        jLabel4 = new javax.swing.JLabel();
        date2 = new datechooser.beans.DateChooserCombo();
        consulterventes = new javax.swing.JButton();
        apercuvente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_reche_vente = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        res_vente_comercial = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pourcentage = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        mon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Z-STock | Gestion financière");

        jPanel1.setBackground(new java.awt.Color(37, 204, 247));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion des ventes");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel2.setBackground(new java.awt.Color(37, 204, 247));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Commercial");

        chauf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chauf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tous" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Date entre");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Et");

        consulterventes.setBackground(new java.awt.Color(4, 139, 154));
        consulterventes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        consulterventes.setIcon(new javax.swing.ImageIcon("C:\\Users\\YASSOU\\Desktop\\developpement\\imagegestion_stock\\consulter (3).jpg")); // NOI18N
        consulterventes.setText("Consulter");
        consulterventes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulterventesActionPerformed(evt);
            }
        });

        apercuvente.setBackground(new java.awt.Color(4, 139, 154));
        apercuvente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        apercuvente.setIcon(new javax.swing.ImageIcon("C:\\Users\\YASSOU\\Desktop\\developpement\\imagegestion_stock\\apercu.png")); // NOI18N
        apercuvente.setText("Aperçu facture");
        apercuvente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apercuventeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(apercuvente, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consulterventes, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(chauf, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(25, 25, 25)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(date1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(date2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(chauf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(date1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(consulterventes, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(apercuvente, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        table_reche_vente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° facture", "Date facture", "Secteur", "Montant", "Commercial"
            }
        ));
        table_reche_vente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_reche_venteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_reche_vente);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Total : ");

        res_vente_comercial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        res_vente_comercial.setText("0");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/monstock/precedent (1).png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Marge %: ");

        pourcentage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pourcentage.setText("0");
        pourcentage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pourcentageKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Montant :");

        mon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(453, 453, 453)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(res_vente_comercial, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pourcentage, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mon, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(res_vente_comercial, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(pourcentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consulterventesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulterventesActionPerformed
      
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
          SimpleDateFormat sdf1=new SimpleDateFormat("yyyy-MM-dd");
        String date_de=sdf.format(date1.getSelectedDate().getTime());
        String date_a=sdf1.format(date2.getSelectedDate().getTime());
        
        DefaultTableModel model1=(DefaultTableModel) table_reche_vente.getModel();
        while (model1.getRowCount()>0)

        {
            for(int i=0;i<model1.getRowCount();i++)
            {
                model1.removeRow(0);
            }
        }

        String rq_vente;
        if(chauf.getSelectedItem().equals("Tous")){
            rq_vente="SELECT num_facture, date_vente, secteur, sum(montant) as mon , commercial FROM vente where date_vente BETWEEN '"+date_de+"' AND '"+date_a+"' GROUP BY num_facture ";
        }
        else{
            rq_vente="SELECT num_facture, date_vente, secteur, sum(montant) as mon , commercial FROM vente WHERE date_vente BETWEEN '"+date_de+"' AND '"+date_a+"' and commercial='"+chauf.getSelectedItem()+"' GROUP BY num_facture";
        }

        try{
            stm=maconx.obtenircnx().createStatement();
            ResultSet res=stm.executeQuery(rq_vente);
            while(res.next()){
                Vector v=new Vector();
                for(int i=0;i<model1.getColumnCount();i++){
                    v.add(res.getString("num_facture"));
                    v.add(res.getString("date_vente"));
                    v.add(res.getString("secteur"));
                    v.add(res.getString("mon"));
                    v.add(res.getString("commercial"));
                }
                model1.addRow(v);
            }

        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
            return;
        }
        table_reche_vente.setModel(model1);
        int s = 0;
        for(int j=0;j<table_reche_vente.getRowCount();j++){
            s+=Integer.parseInt(model1.getValueAt(j, 3).toString());
        }
        res_vente_comercial.setText(String.valueOf(s));
        mon.setText("");
        pourcentage.setText("");
    }//GEN-LAST:event_consulterventesActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void apercuventeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apercuventeActionPerformed
       
         if(table_reche_vente.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this,"Voulez vous selectionnée un ligne pour le consulter");
            return;
        }
        else {
                apercu_vente mod=new apercu_vente();

              DefaultTableModel model2=(DefaultTableModel) mod.table_apercu_vente.getModel();
         
    String ch=(model.getValueAt(table_reche_vente.getSelectedRow(),0).toString());
    
          String d=(model.getValueAt(table_reche_vente.getSelectedRow(),1).toString());
         String s=(model.getValueAt(table_reche_vente.getSelectedRow(),2).toString());;
        String co=(model.getValueAt(table_reche_vente.getSelectedRow(),4).toString());
        
        mod.date_vente.setText(d);
        mod.facture.setText(ch);
        mod.sec.setText(s);
        mod.com.setText(co);
        
      
         String rq="select desg, prix , qte_vente, montant from vente where num_facture='"+ch+"' ";
         
         try{
              stm=maconx.obtenircnx().createStatement();
            ResultSet res=stm.executeQuery(rq);
            while(res.next()){
                Vector v= new Vector();
                 for(int i=1;i<=model.getColumnCount();i++)
                 {
                        
             
                 v.add(res.getString("desg"));     
                v.add(res.getString("prix"));
                 v.add(res.getString("qte_vente"));
                 v.add(res.getString("montant"));
     
            }
                  model2.addRow(v);
            }
         
         }catch(SQLException ex){
             System.out.println(ex);
         }
         mod.table_apercu_vente.setModel(model2);
         
         int somme=0;
         
         for(int i=0;i<mod.table_apercu_vente.getRowCount();i++){
             somme+=Integer.parseInt(model2.getValueAt(i, 3).toString());
         }
         mod.total.setText(String.valueOf(somme));
          mod.setVisible(true);
        }
        
    }//GEN-LAST:event_apercuventeActionPerformed

    private void table_reche_venteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_reche_venteMouseClicked
       
       
    }//GEN-LAST:event_table_reche_venteMouseClicked

    private void pourcentageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pourcentageKeyReleased
      
        Double s, t, m;
        t=Double.parseDouble(res_vente_comercial.getText());
        m=Double.parseDouble(pourcentage.getText());
        s=(t*m)/100;
        mon.setText(String.valueOf(s));
    }//GEN-LAST:event_pourcentageKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gestionfinanciere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gestionfinanciere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gestionfinanciere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gestionfinanciere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gestionfinanciere().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apercuvente;
    private javax.swing.JComboBox<String> chauf;
    private javax.swing.JButton consulterventes;
    private datechooser.beans.DateChooserCombo date1;
    private datechooser.beans.DateChooserCombo date2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mon;
    private javax.swing.JTextField pourcentage;
    private javax.swing.JLabel res_vente_comercial;
    private javax.swing.JTable table_reche_vente;
    // End of variables declaration//GEN-END:variables
}
