/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monstock;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YASSOU
 */
public class getsionachat extends javax.swing.JFrame {

    Statement stm, stm1;
    connexion maconx = new connexion();
    DefaultTableModel model;
    int selectedrow;
    int reste;
    int stk_av_fac;
    int sect_tab_stock;
    boolean verifnew;

    /**
     * Creates new form getsionachat
     */
    public getsionachat() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        this.setLocationRelativeTo(null);
        setResizable(false);
        icon();
        model = (DefaultTableModel) tab_achat.getModel();
        listefournisseur();
        numfac.requestFocus();
    }

    void icon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo1.jpg")));
    }

    private void listefournisseur() {
        String req_affiche = "select * from fournisseur";
        try {
            stm = maconx.obtenircnx().createStatement();
            ResultSet res = stm.executeQuery(req_affiche);
            while (res.next()) {

                String name = res.getString("nom_soc");
                four.addItem(name);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }

    public void controle_champs(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numfac = new javax.swing.JTextField();
        datechosser = new datechooser.beans.DateChooserCombo();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        codeart = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        des = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        four = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        ht = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tva = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        remise = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ttc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        qte = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        mon = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_achat = new javax.swing.JTable();
        ajoutvente = new javax.swing.JButton();
        modifiervente = new javax.swing.JButton();
        supprimervente = new javax.swing.JButton();
        modifiervente2 = new javax.swing.JButton();
        res = new javax.swing.JLabel();
        apercuachat = new javax.swing.JButton();
        enregistrer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Z-STock | Gestion d'achat");

        jPanel1.setBackground(new java.awt.Color(37, 204, 247));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Facture N°");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        numfac.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        numfac.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\YASSOU\\Desktop\\developpement\\imagegestion_stock\\precedent (1).png")); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(37, 204, 247));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Code Article");

        codeart.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        codeart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codeartKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                codeartKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Désignation");

        des.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Fournisseur");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Prix HT");

        ht.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ht.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                htKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("TVA %");

        tva.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tvaKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Remise");

        remise.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        remise.setText("0");
        remise.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                remiseKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                remiseKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Prix TTC");

        ttc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ttc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ttcKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Quantité");

        qte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        qte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qteKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Montant");

        mon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                monKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("ID");
        jLabel12.setToolTipText("");

        id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel12))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(codeart)
                        .addComponent(des)
                        .addComponent(four, 0, 180, Short.MAX_VALUE)
                        .addComponent(ht, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tva)
                        .addComponent(remise)
                        .addComponent(ttc)
                        .addComponent(qte)
                        .addComponent(mon))
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codeart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(remise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ttc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(mon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        tab_achat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code Article", "Désignation", "Prix HT", "TVA", "Remise", "Prix TTC", "Quantité", "Montant"
            }
        ));
        tab_achat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_achatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_achat);

        ajoutvente.setBackground(new java.awt.Color(4, 139, 154));
        ajoutvente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ajoutvente.setIcon(new javax.swing.ImageIcon("C:\\Users\\YASSOU\\Desktop\\developpement\\application gestion des produits\\gestion des produit\\src\\gestion\\des\\produit\\icon\\ajouter.png")); // NOI18N
        ajoutvente.setText("Ajouter");
        ajoutvente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutventeActionPerformed(evt);
            }
        });

        modifiervente.setBackground(new java.awt.Color(4, 139, 154));
        modifiervente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modifiervente.setIcon(new javax.swing.ImageIcon("C:\\Users\\YASSOU\\Desktop\\developpement\\imagegestion_stock\\modif (1).png")); // NOI18N
        modifiervente.setText("Modifier");
        modifiervente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierventeActionPerformed(evt);
            }
        });

        supprimervente.setBackground(new java.awt.Color(4, 139, 154));
        supprimervente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        supprimervente.setIcon(new javax.swing.ImageIcon("C:\\Users\\YASSOU\\Desktop\\developpement\\imagegestion_stock\\supprime (1).png")); // NOI18N
        supprimervente.setText("Supprimer");
        supprimervente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerventeActionPerformed(evt);
            }
        });

        modifiervente2.setBackground(new java.awt.Color(4, 139, 154));
        modifiervente2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modifiervente2.setIcon(new javax.swing.ImageIcon("C:\\Users\\YASSOU\\Desktop\\developpement\\application gestion des produits\\gestion des produit\\src\\gestion\\des\\produit\\icon\\noveau.png")); // NOI18N
        modifiervente2.setText("Nouvel Achat");
        modifiervente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifiervente2ActionPerformed(evt);
            }
        });

        res.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        res.setText("Total : ");

        apercuachat.setBackground(new java.awt.Color(4, 139, 154));
        apercuachat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        apercuachat.setIcon(new javax.swing.ImageIcon("C:\\Users\\YASSOU\\Desktop\\developpement\\imagegestion_stock\\apercu.png")); // NOI18N
        apercuachat.setText("Aperçu");
        apercuachat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apercuachatActionPerformed(evt);
            }
        });

        enregistrer.setBackground(new java.awt.Color(4, 139, 154));
        enregistrer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enregistrer.setIcon(new javax.swing.ImageIcon("C:\\Users\\YASSOU\\Desktop\\developpement\\imagegestion_stock\\enregistrer.png")); // NOI18N
        enregistrer.setText("Enregistrer");
        enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(431, 431, 431)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numfac, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(datechosser, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ajoutvente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(enregistrer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(modifiervente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(supprimervente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(apercuachat, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(modifiervente2)
                                .addGap(91, 91, 91)
                                .addComponent(res, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datechosser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numfac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ajoutvente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(modifiervente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(supprimervente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(apercuachat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(modifiervente2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(res))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
            
        if (tab_achat.getRowCount()==0){
             this.dispose();
        }else{
  if  (JOptionPane.showConfirmDialog(this,"voulez-vous quiter!! facture n'est pas enregistrer...", "Verification!!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION)
                {

                  this.dispose();
  }      
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void ajoutventeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutventeActionPerformed

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        String date = sdf.format(datechosser.getSelectedDate().getTime());
        Statement stm_stock;

        String n = numfac.getText();
        String c = codeart.getText();
        String d = des.getText();
        String f = (String) four.getSelectedItem();
        String h = ht.getText();
        String ta = tva.getText();
        String r = remise.getText();
        String tc = ttc.getText();
        String q = qte.getText();
        String m = mon.getText();

        int s = 0;
        if ((n.equals("")) || (c.equals("")) || (d.equals("")) || (f.equals("")) || (h.equals("")) || (ta.equals("")) || (r.equals("")) || (tc.equals("")) || (q.equals("")) || (m.equals(""))) {
            JOptionPane.showMessageDialog(null, "remplir les champs");
            return;
        } else {
               // JOptionPane.showMessageDialog(this, "Ajout reussite");
                  model.addRow(new Object[]{c, d, h, ta, r, tc, q, m});
                  id.setText("");
                 codeart.setText("");
                des.setText("");
                ht.setText("");
                remise.setText("0");
                tva.setText("");
                ttc.setText("");
                qte.setText("");
                mon.setText("");
                codeart.requestFocus();
        }

      

        int montant = 0;

        for (int j = 0; j < tab_achat.getRowCount(); j++) {
            montant = montant + (Integer.parseInt(tab_achat.getValueAt(j, 7).toString()));
        }
        res.setText("Total: " + String.valueOf(montant));
    }//GEN-LAST:event_ajoutventeActionPerformed
 

    private void codeartKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeartKeyPressed

    }//GEN-LAST:event_codeartKeyPressed

    private void qteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qteKeyReleased
        int x, c, a;
       
            c =  Integer.parseInt(ttc.getText());
            a =  Integer.parseInt(qte.getText());
            x = c * a;
            mon.setText(String.valueOf(x));
            // TODO add your handling code here:
    }//GEN-LAST:event_qteKeyReleased

    private void qteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qteKeyTyped
        controle_champs(evt);
    }//GEN-LAST:event_qteKeyTyped

    private void htKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_htKeyTyped
        controle_champs(evt);          // TODO add your handling code here:
    }//GEN-LAST:event_htKeyTyped

    private void tvaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tvaKeyTyped
        controle_champs(evt);          // TODO add your handling code here:
    }//GEN-LAST:event_tvaKeyTyped

    private void remiseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_remiseKeyTyped
        //controle_champs(evt);          // TODO add your handling code here:
    }//GEN-LAST:event_remiseKeyTyped

    private void ttcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ttcKeyTyped
        controle_champs(evt);          // TODO add your handling code here:
    }//GEN-LAST:event_ttcKeyTyped

    private void monKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monKeyTyped
        controle_champs(evt);          // TODO add your handling code here:
    }//GEN-LAST:event_monKeyTyped

    private void codeartKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeartKeyReleased
        String req = "select desg_art from stock where code_art='" + codeart.getText() + "'";
        try {
            stm = maconx.obtenircnx().createStatement();
            ResultSet res = stm.executeQuery(req);
            if (res.next()) {
                des.setText(res.getString("desg_art"));
                ht.requestFocus();
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }          // TODO add your handling code here:
    }//GEN-LAST:event_codeartKeyReleased

    private void tab_achatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_achatMouseClicked

        selectedrow = tab_achat.getSelectedRow();

                codeart.setText(model.getValueAt(tab_achat.getSelectedRow(), 0).toString());
                des.setText(model.getValueAt(tab_achat.getSelectedRow(), 1).toString());
                ht.setText(model.getValueAt(tab_achat.getSelectedRow(), 2).toString());
                tva.setText(model.getValueAt(tab_achat.getSelectedRow(), 3).toString());
                remise.setText(model.getValueAt(tab_achat.getSelectedRow(), 4).toString());
                ttc.setText(model.getValueAt(tab_achat.getSelectedRow(), 5).toString());
                qte.setText(model.getValueAt(tab_achat.getSelectedRow(), 6).toString());
                mon.setText(model.getValueAt(tab_achat.getSelectedRow(), 7).toString());

    }//GEN-LAST:event_tab_achatMouseClicked

    public void update_achat() {
 
        String c = codeart.getText();
        String d = des.getText();    
        String h = ht.getText();
        String ta = tva.getText();
        String r = remise.getText();
        String tc = ttc.getText();
        String q = qte.getText();
        String m = mon.getText();

       
            JOptionPane.showMessageDialog(null,"modification reusite");
            model.setValueAt(c, tab_achat.getSelectedRow(), 0);
            model.setValueAt(d, tab_achat.getSelectedRow(), 1);
            model.setValueAt(h, tab_achat.getSelectedRow(), 2);
            model.setValueAt(ta, tab_achat.getSelectedRow(), 3);
            model.setValueAt(r, tab_achat.getSelectedRow(), 4);
            model.setValueAt(tc, tab_achat.getSelectedRow(), 5);
            model.setValueAt(q, tab_achat.getSelectedRow(), 6);
            model.setValueAt(m, tab_achat.getSelectedRow(), 7);


    }
    private void modifierventeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierventeActionPerformed

        if (tab_achat.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selectionnée une ligne pour le modifier!!!!");

        } else {

            String n = numfac.getText();
            String c = codeart.getText();
            String d = des.getText();
            String h = ht.getText();
            String ta = tva.getText();
            String r = remise.getText();
            String tc = ttc.getText();
            String q = qte.getText();
            String m = mon.getText();

            int s = 0;

       if (JOptionPane.showConfirmDialog(this, "voulez-vous modifier", "Verification!!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                        
                  update_achat();

                    id.setText("");
                    codeart.setText("");
                    des.setText("");
                    ht.setText("");
                    remise.setText("");
                    ttc.setText("");
                    qte.setText("");
                    mon.setText("");
                    codeart.requestFocus();

                    }
                    
               
       
        int montant = 0;

        for (int j = 0; j < tab_achat.getRowCount(); j++) {
            montant = montant + (Integer.parseInt((String) tab_achat.getValueAt(j, 7)));
        }
        res.setText("Total: " + String.valueOf(montant));
        }
    }//GEN-LAST:event_modifierventeActionPerformed

    private void supprimerventeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerventeActionPerformed
      
         if(tab_achat.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this,"Selectionnée une ligne pour le supprimer!!!!");
            return;
        }
       
            if  (JOptionPane.showConfirmDialog(this,"voulez-vous supprimer", "Verification!!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION)
                 {
               JOptionPane.showMessageDialog(this, "Suppression réussite");
                       model.removeRow(selectedrow);
            codeart.setText("");
            des.setText("");          
            ht.setText("");
            tva.setText("");
            remise.setText("0");
            ttc.setText("");
            qte.setText("");
            mon.setText("");
            codeart.requestFocus();
            id.setText("");
          
                 }
        
        
      
             int montant = 0;
       
       for(int j=0;j<tab_achat.getRowCount();j++)
       {
           montant=montant+ (Integer.parseInt((String) tab_achat.getValueAt(j,7)));
       }
      res.setText("Total: " + String.valueOf(montant));
    }//GEN-LAST:event_supprimerventeActionPerformed

    private void modifiervente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifiervente2ActionPerformed
      if (tab_achat.getRowCount()==0){
             return;
        }else{
  if  (JOptionPane.showConfirmDialog(this,"Facture n'est pas enregistrer... Voulez-vous annuler", "Verification!!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION)
                {

                while (model.getRowCount()>0)
                {
                    for(int i=0;i<model.getRowCount();i++)
                    {
                        model.removeRow(0);
                    }
                }
                  numfac.setText("");
         id.setText(""); 
         remise.setText("");
         codeart.setText("");  tva.setText("");
           des.setText("");   ttc.setText("");
           ht.setText("");      mon.setText("");
            res.setText("Total: 0");
  }      
        }
         
       
    }//GEN-LAST:event_modifiervente2ActionPerformed

    private void apercuachatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apercuachatActionPerformed
         Object row[]=new Object [3];
        
        apercu_fac frm =new apercu_fac();
        
        DefaultTableModel model2 = (DefaultTableModel)frm.jTable1.getModel();
        if(tab_achat.getRowCount()==0){
            JOptionPane.showMessageDialog(this,"Tableau vide rien a imprimer!!!");
            return;
        }
        else{
            
            frm.fournisseur.setText(four.getSelectedItem().toString());
                 for(int i=0;i<tab_achat.getRowCount();i++)
        {
            frm.nfact.setText(numfac.getText());
            frm.dt.setText(datechosser.getText());
       
        row[0]=model.getValueAt(i, 1);
       
        row[1]=model.getValueAt(i, 5);
        row[2]=model.getValueAt(i, 7);
       
         model2.addRow(row);
         
        }
        frm.jTable1.setModel(model2);
       
        int s=0;
       for(int j=0;j<frm.jTable1.getRowCount();j++){
       s+=Integer.parseInt(model2.getValueAt(j, 2).toString());
       frm.res_vente_impriment.setText(String.valueOf(s));
       }
       
        frm.setVisible(true);
        }
    }//GEN-LAST:event_apercuachatActionPerformed

    private void remiseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_remiseKeyReleased
        int s,r,res;
        
        s=(Integer.parseInt(ht.getText())+(Integer.parseInt(ht.getText())*(Integer.parseInt(tva.getText()))/100));
        if(!(remise.getText().equals(""))){
             r=((Integer.parseInt(remise.getText()))*s/100);
        res=s-r;
        ttc.setText(String.valueOf(res));
        }else{
             ttc.setText(String.valueOf(s));
        }
        qte.requestFocus();
       
    }//GEN-LAST:event_remiseKeyReleased

    private void enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerActionPerformed
         
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy/MM/dd");
        String date=sdf.format(datechosser.getSelectedDate().getTime());
        int s = 0;
           Statement stm_stock;
           if (tab_achat.getRowCount()==0) {
            JOptionPane.showMessageDialog(null, "Facture vide !!!");
            return;
        }else{
          if  (JOptionPane.showConfirmDialog(this,"voulez-vous Enregistrer!! ..", "Verification!!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION)
                {     
          //debut insert in table facture 
          
          for(int i=0;i<tab_achat.getRowCount(); i++){
               String f = (String) four.getSelectedItem();
              String n=numfac.getText();
             String c=(tab_achat.getValueAt(i,0).toString());
              String d=(tab_achat.getValueAt(i,1).toString());
               String h=(tab_achat.getValueAt(i,2).toString());
                String ta=(tab_achat.getValueAt(i,3).toString());
                 String r=(tab_achat.getValueAt(i,4).toString());
                  String tc=(tab_achat.getValueAt(i,5).toString());
                   String q=(tab_achat.getValueAt(i,6).toString());
                  String m=(tab_achat.getValueAt(i,7).toString());
                  
String requete = "INSERT INTO facture (num_fac, date_fac, code_art, desg, fourni, prix_ht, tva, remise, prix_ttc, qte, montant) VALUES('" + n + "','" + date + "','" + c + "','" + d + "','" + f + "','" + Double.parseDouble(h) + "','" + Double.parseDouble(ta) + "','" + Double.parseDouble(r) + "','" + Double.parseDouble(tc) + "','" + Integer.parseInt(q) + "','" + Double.parseDouble(m) + "')";    
             try{
                 stm=maconx.obtenircnx().createStatement();
                 stm.executeUpdate(requete);
                 
             }catch(SQLException ex){
                 JOptionPane.showMessageDialog(this, ex.getMessage());
             }        
             
        }
            //fin insert in table facture 
            
     //debut update stock
     
            for(int j=0;j<tab_achat.getRowCount(); j++){
              
                String f = (String) four.getSelectedItem();
                String n=numfac.getText();
                String c=(tab_achat.getValueAt(j,0).toString());
                  String d=(tab_achat.getValueAt(j,1).toString());
                  String h=(tab_achat.getValueAt(j,2).toString());
                   String ta=(tab_achat.getValueAt(j,3).toString());
                   String r=(tab_achat.getValueAt(j,4).toString());
                   String tc=(tab_achat.getValueAt(j,5).toString());
                   String q=(tab_achat.getValueAt(j,6).toString());
                  String m=(tab_achat.getValueAt(j,7).toString());
                  
               String sel_stock = "SELECT qte FROM stock where code_art='" + c + "'";
            try {
                stm = maconx.obtenircnx().createStatement();
                ResultSet res_stock = stm.executeQuery(sel_stock);

                if (res_stock.next()) {
                    s = res_stock.getInt("qte") + Integer.parseInt(q);
                   String req_update_stock = "UPDATE stock SET  desg_art='" + d + "', qte='" + s + "' where code_art='" + c + "' ";
                    stm_stock = maconx.obtenircnx().createStatement();
                    stm_stock.executeUpdate(req_update_stock);
                    //JOptionPane.showMessageDialog(this,s);
                    
                } else {
                    String req_insert_stock = "INSERT INTO stock (code_art, desg_art, qte, prix_vente) VALUES ('" + c + "', '" + d + "', '" + q + "', '" + tc + "')";
                    stm_stock = maconx.obtenircnx().createStatement();
                    stm_stock.executeUpdate(req_insert_stock);
                    
                }
            } catch (SQLException ex) {
                System.out.println(ex);
            }   
        }
            JOptionPane.showMessageDialog(this, "Enregistrement de facture réussite");
   //fin update stock     
         while (model.getRowCount()>0)
                {
                    for(int i=0;i<model.getRowCount();i++)
                    {
                        model.removeRow(0);
                    }
                } 
         numfac.setText("");
                  id.setText("");
                 codeart.setText("");
                des.setText("");
                ht.setText("");
                remise.setText("0");
                tva.setText("");
                ttc.setText("");
                qte.setText("");
                mon.setText("");
                res.setText("Total: 0");
           
           }
           }
    }//GEN-LAST:event_enregistrerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getsionachat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(getsionachat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(getsionachat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(getsionachat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new getsionachat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajoutvente;
    private javax.swing.JButton apercuachat;
    private javax.swing.JTextField codeart;
    private datechooser.beans.DateChooserCombo datechosser;
    private javax.swing.JTextField des;
    private javax.swing.JButton enregistrer;
    private javax.swing.JComboBox<String> four;
    private javax.swing.JTextField ht;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifiervente;
    private javax.swing.JButton modifiervente2;
    private javax.swing.JTextField mon;
    private javax.swing.JTextField numfac;
    private javax.swing.JTextField qte;
    private javax.swing.JTextField remise;
    private javax.swing.JLabel res;
    private javax.swing.JButton supprimervente;
    private javax.swing.JTable tab_achat;
    private javax.swing.JTextField ttc;
    private javax.swing.JTextField tva;
    // End of variables declaration//GEN-END:variables
}
